/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/v1/api-keys": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Api Keys */
        readonly get: operations["list_api_keys_api_v1_api_keys_get"];
        readonly put?: never;
        /** Create Api Key */
        readonly post: operations["create_api_key_api_v1_api_keys_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/api-keys/{key_id}/revoke": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Revoke Api Key */
        readonly post: operations["revoke_api_key_api_v1_api_keys__key_id__revoke_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/audit-logs": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Audit Logs */
        readonly get: operations["list_audit_logs_api_v1_audit_logs_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/change-password": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Change Password */
        readonly post: operations["change_password_api_v1_auth_change_password_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/login": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Login */
        readonly post: operations["login_api_v1_auth_login_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/logout": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Logout */
        readonly post: operations["logout_api_v1_auth_logout_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/me": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Me */
        readonly get: operations["me_api_v1_auth_me_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/refresh": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Refresh */
        readonly post: operations["refresh_api_v1_auth_refresh_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/events": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Events */
        readonly get: operations["list_events_api_v1_events_get"];
        readonly put?: never;
        /** Create Event */
        readonly post: operations["create_event_api_v1_events_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/events/{event_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Event */
        readonly get: operations["get_event_api_v1_events__event_id__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/events/bulk": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Create Events Bulk */
        readonly post: operations["create_events_bulk_api_v1_events_bulk_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Health Check */
        readonly get: operations["health_check_api_v1_health_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/incidents": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Incidents */
        readonly get: operations["list_incidents_api_v1_incidents_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/incidents/{incident_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Incident */
        readonly get: operations["get_incident_api_v1_incidents__incident_id__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/incidents/{incident_id}/investigations": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Incident Investigations */
        readonly get: operations["list_incident_investigations_api_v1_incidents__incident_id__investigations_get"];
        readonly put?: never;
        /** Request Investigation */
        readonly post: operations["request_investigation_api_v1_incidents__incident_id__investigations_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/investigations/{investigation_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Investigation */
        readonly get: operations["get_investigation_api_v1_investigations__investigation_id__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/mitre/rules/{rule_id}/techniques": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Rule Techniques */
        readonly get: operations["get_rule_techniques_api_v1_mitre_rules__rule_id__techniques_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/mitre/techniques": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Techniques */
        readonly get: operations["list_techniques_api_v1_mitre_techniques_get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/mitre/techniques/{external_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Technique */
        readonly get: operations["get_technique_api_v1_mitre_techniques__external_id__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/users": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Users */
        readonly get: operations["list_users_api_v1_users_get"];
        readonly put?: never;
        /** Create User */
        readonly post: operations["create_user_api_v1_users_post"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/users/{user_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get User */
        readonly get: operations["get_user_api_v1_users__user_id__get"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        /** Update User */
        readonly patch: operations["update_user_api_v1_users__user_id__patch"];
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertResponse */
        readonly AlertResponse: {
            /** Confidence */
            readonly confidence: number;
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
            /** Description */
            readonly description: string;
            /**
             * Event Id
             * Format: uuid
             */
            readonly event_id: string;
            /** Evidence */
            readonly evidence: {
                readonly [key: string]: unknown;
            };
            /**
             * First Seen
             * Format: date-time
             */
            readonly first_seen: string;
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
            /**
             * Last Seen
             * Format: date-time
             */
            readonly last_seen: string;
            /** Rule Id */
            readonly rule_id: string;
            /** Severity */
            readonly severity: string;
            /** Source Ip */
            readonly source_ip: string | null;
            /** Status */
            readonly status: string;
            /** Title */
            readonly title: string;
            /** Username */
            readonly username: string | null;
        };
        /** ApiKeyCreate */
        readonly ApiKeyCreate: {
            /** Expires At */
            readonly expires_at?: string | null;
            /** Name */
            readonly name: string;
            /** Scopes */
            readonly scopes?: readonly "events:write"[];
        };
        /** ApiKeyCreatedResponse */
        readonly ApiKeyCreatedResponse: {
            /** Api Key */
            readonly api_key: string;
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
            /**
             * Created By
             * Format: uuid
             */
            readonly created_by: string;
            /** Expires At */
            readonly expires_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
            /** Is Active */
            readonly is_active: boolean;
            /** Last Used At */
            readonly last_used_at: string | null;
            /** Name */
            readonly name: string;
            /** Prefix */
            readonly prefix: string;
            /** Revoked At */
            readonly revoked_at: string | null;
            /** Scopes */
            readonly scopes: readonly string[];
        };
        /** ApiKeyListResponse */
        readonly ApiKeyListResponse: {
            /** Items */
            readonly items: readonly components["schemas"]["ApiKeyResponse"][];
            /** Limit */
            readonly limit: number;
            /** Offset */
            readonly offset: number;
            /** Total */
            readonly total: number;
        };
        /** ApiKeyResponse */
        readonly ApiKeyResponse: {
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
            /**
             * Created By
             * Format: uuid
             */
            readonly created_by: string;
            /** Expires At */
            readonly expires_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
            /** Is Active */
            readonly is_active: boolean;
            /** Last Used At */
            readonly last_used_at: string | null;
            /** Name */
            readonly name: string;
            /** Prefix */
            readonly prefix: string;
            /** Revoked At */
            readonly revoked_at: string | null;
            /** Scopes */
            readonly scopes: readonly string[];
        };
        /** AuditLogListResponse */
        readonly AuditLogListResponse: {
            /** Items */
            readonly items: readonly components["schemas"]["AuditLogResponse"][];
            /** Limit */
            readonly limit: number;
            /** Offset */
            readonly offset: number;
            /** Total */
            readonly total: number;
        };
        /** AuditLogResponse */
        readonly AuditLogResponse: {
            /** Action */
            readonly action: string;
            /** Actor Id */
            readonly actor_id: string | null;
            /** Actor Label */
            readonly actor_label: string | null;
            /** Actor Type */
            readonly actor_type: string;
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
            /** Details */
            readonly details: {
                readonly [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
            /** Method */
            readonly method: string | null;
            /** Outcome */
            readonly outcome: string;
            /** Path */
            readonly path: string | null;
            /** Request Id */
            readonly request_id: string | null;
            /** Resource Id */
            readonly resource_id: string | null;
            /** Resource Type */
            readonly resource_type: string | null;
            /** Source Ip */
            readonly source_ip: string | null;
            /** User Agent */
            readonly user_agent: string | null;
        };
        /** Body_login_api_v1_auth_login_post */
        readonly Body_login_api_v1_auth_login_post: {
            /** Client Id */
            readonly client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            readonly client_secret?: string | null;
            /** Grant Type */
            readonly grant_type?: string | null;
            /**
             * Password
             * Format: password
             */
            readonly password: string;
            /**
             * Scope
             * @default
             */
            readonly scope: string;
            /** Username */
            readonly username: string;
        };
        /** ChangePasswordRequest */
        readonly ChangePasswordRequest: {
            /** Current Password */
            readonly current_password: string;
            /** New Password */
            readonly new_password: string;
        };
        /** EventBulkCreate */
        readonly EventBulkCreate: {
            /** Events */
            readonly events: readonly components["schemas"]["EventCreate"][];
        };
        /** EventBulkIngestResponse */
        readonly EventBulkIngestResponse: {
            /**
             * Accepted
             * @default true
             */
            readonly accepted: boolean;
            /** Count */
            readonly count: number;
            /** Events */
            readonly events: readonly components["schemas"]["EventIngestResponse"][];
        };
        /** EventCreate */
        readonly EventCreate: {
            /** Action */
            readonly action?: string | null;
            /** Bytes Received */
            readonly bytes_received?: number | null;
            /** Bytes Sent */
            readonly bytes_sent?: number | null;
            /**
             * Category
             * @enum {string}
             */
            readonly category: "authentication" | "network" | "cloud" | "application" | "file_access" | "privilege_change" | "process" | "api";
            /** Country */
            readonly country?: string | null;
            /** Destination Ip */
            readonly destination_ip?: string | null;
            /** Destination Port */
            readonly destination_port?: number | null;
            /** Device Id */
            readonly device_id?: string | null;
            /** Event Id */
            readonly event_id?: string | null;
            /**
             * Event Type
             * @enum {string}
             */
            readonly event_type: "login_success" | "login_failure" | "logout" | "api_request" | "api_error" | "file_access" | "file_download" | "privilege_change" | "network_connection" | "network_scan" | "resource_access" | "account_created" | "account_deleted" | "password_changed";
            /** Hostname */
            readonly hostname?: string | null;
            /** Metadata */
            readonly metadata?: {
                readonly [key: string]: unknown;
            };
            /** Raw Payload */
            readonly raw_payload?: {
                readonly [key: string]: unknown;
            } | null;
            /** Resource */
            readonly resource?: string | null;
            /** Resource Type */
            readonly resource_type?: string | null;
            /** Severity */
            readonly severity?: ("low" | "medium" | "high" | "critical") | null;
            /** Source */
            readonly source: string;
            /** Source Ip */
            readonly source_ip?: string | null;
            /** Source Port */
            readonly source_port?: number | null;
            /** Source Type */
            readonly source_type: string;
            /** Status */
            readonly status?: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            readonly timestamp: string;
            /** User Agent */
            readonly user_agent?: string | null;
            /** User Id */
            readonly user_id?: string | null;
            /** Username */
            readonly username?: string | null;
        };
        /** EventIngestResponse */
        readonly EventIngestResponse: {
            /**
             * Accepted
             * @default true
             */
            readonly accepted: boolean;
            /** Event Id */
            readonly event_id: string;
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
        };
        /** EventListResponse */
        readonly EventListResponse: {
            /** Items */
            readonly items: readonly components["schemas"]["EventResponse"][];
            /** Limit */
            readonly limit: number;
            /** Offset */
            readonly offset: number;
            /** Total */
            readonly total: number;
        };
        /** EventResponse */
        readonly EventResponse: {
            /** Action */
            readonly action: string | null;
            /** Bytes Received */
            readonly bytes_received: number | null;
            /** Bytes Sent */
            readonly bytes_sent: number | null;
            /** Category */
            readonly category: string;
            /** Country */
            readonly country: string | null;
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
            /** Destination Ip */
            readonly destination_ip: string | null;
            /** Destination Port */
            readonly destination_port: number | null;
            /** Device Id */
            readonly device_id: string | null;
            /** Event Id */
            readonly event_id: string;
            /** Event Metadata */
            readonly event_metadata: {
                readonly [key: string]: unknown;
            };
            /** Event Type */
            readonly event_type: string;
            /** Hostname */
            readonly hostname: string | null;
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
            /** Raw Payload */
            readonly raw_payload: {
                readonly [key: string]: unknown;
            };
            /**
             * Received At
             * Format: date-time
             */
            readonly received_at: string;
            /** Resource */
            readonly resource: string | null;
            /** Resource Type */
            readonly resource_type: string | null;
            /** Severity */
            readonly severity: string | null;
            /** Source */
            readonly source: string;
            /** Source Ip */
            readonly source_ip: string | null;
            /** Source Port */
            readonly source_port: number | null;
            /** Source Type */
            readonly source_type: string;
            /** Status */
            readonly status: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            readonly timestamp: string;
            /** User Agent */
            readonly user_agent: string | null;
            /** User Id */
            readonly user_id: string | null;
            /** Username */
            readonly username: string | null;
        };
        /** EvidenceFinding */
        readonly EvidenceFinding: {
            /** Confidence */
            readonly confidence: number;
            /** Evidence Refs */
            readonly evidence_refs?: readonly string[];
            /**
             * Severity
             * @enum {string}
             */
            readonly severity: "low" | "medium" | "high" | "critical";
            /** Summary */
            readonly summary: string;
            /** Title */
            readonly title: string;
        };
        /** HealthResponse */
        readonly HealthResponse: {
            /** Database */
            readonly database: string;
            /** Redis */
            readonly redis: string;
            /** Status */
            readonly status: string;
        };
        /** HTTPValidationError */
        readonly HTTPValidationError: {
            /** Detail */
            readonly detail?: readonly components["schemas"]["ValidationError"][];
        };
        /** IncidentDetail */
        readonly IncidentDetail: {
            /** Alerts */
            readonly alerts: readonly components["schemas"]["AlertResponse"][];
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
            /** Description */
            readonly description: string;
            /**
             * First Seen
             * Format: date-time
             */
            readonly first_seen: string;
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
            /**
             * Last Seen
             * Format: date-time
             */
            readonly last_seen: string;
            /** Primary Source Ip */
            readonly primary_source_ip: string | null;
            /** Primary Username */
            readonly primary_username: string | null;
            /** Risk Score */
            readonly risk_score: number;
            /** Severity */
            readonly severity: string;
            /** Status */
            readonly status: string;
            /** Techniques */
            readonly techniques: readonly components["schemas"]["MitreTechniqueResponse"][];
            /** Timeline */
            readonly timeline: readonly components["schemas"]["TimelineEntry"][];
            /** Title */
            readonly title: string;
            /**
             * Updated At
             * Format: date-time
             */
            readonly updated_at: string;
        };
        /** IncidentListItem */
        readonly IncidentListItem: {
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
            /** Description */
            readonly description: string;
            /**
             * First Seen
             * Format: date-time
             */
            readonly first_seen: string;
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
            /**
             * Last Seen
             * Format: date-time
             */
            readonly last_seen: string;
            /** Primary Source Ip */
            readonly primary_source_ip: string | null;
            /** Primary Username */
            readonly primary_username: string | null;
            /** Risk Score */
            readonly risk_score: number;
            /** Severity */
            readonly severity: string;
            /** Status */
            readonly status: string;
            /** Title */
            readonly title: string;
            /**
             * Updated At
             * Format: date-time
             */
            readonly updated_at: string;
        };
        /** IncidentListResponse */
        readonly IncidentListResponse: {
            /** Items */
            readonly items: readonly components["schemas"]["IncidentListItem"][];
            /** Limit */
            readonly limit: number;
            /** Offset */
            readonly offset: number;
            /** Total */
            readonly total: number;
        };
        /** InvestigationListResponse */
        readonly InvestigationListResponse: {
            /** Items */
            readonly items: readonly components["schemas"]["InvestigationResponse"][];
        };
        /** InvestigationResponse */
        readonly InvestigationResponse: {
            /** Attempt Count */
            readonly attempt_count: number;
            /** Completed At */
            readonly completed_at: string | null;
            /** Context Hash */
            readonly context_hash: string;
            /** Context Snapshot */
            readonly context_snapshot: {
                readonly [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
            /** Error */
            readonly error: string | null;
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            readonly incident_id: string;
            /** Input Tokens */
            readonly input_tokens: number;
            /** Model */
            readonly model: string;
            /** Output Tokens */
            readonly output_tokens: number;
            /** Prompt Version */
            readonly prompt_version: string;
            /** Provider */
            readonly provider: string;
            /** Provider Response Ids */
            readonly provider_response_ids: readonly string[];
            /**
             * Queued At
             * Format: date-time
             */
            readonly queued_at: string;
            readonly result: components["schemas"]["InvestigationResult"] | null;
            /** Started At */
            readonly started_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            readonly status: "queued" | "running" | "completed" | "failed";
            /**
             * Updated At
             * Format: date-time
             */
            readonly updated_at: string;
            /** Validation Errors */
            readonly validation_errors: readonly string[];
        };
        /** InvestigationResult */
        readonly InvestigationResult: {
            /** Attack Story */
            readonly attack_story: string;
            /** Confidence */
            readonly confidence: number;
            /** Evidence Gaps */
            readonly evidence_gaps: readonly string[];
            /** Executive Summary */
            readonly executive_summary: string;
            /** Findings */
            readonly findings: readonly components["schemas"]["EvidenceFinding"][];
            /** Mitre Context */
            readonly mitre_context: readonly components["schemas"]["MitreContextItem"][];
            /** Recommendations */
            readonly recommendations: readonly components["schemas"]["Recommendation"][];
            readonly risk_analysis: components["schemas"]["RiskAnalysis"];
        };
        /** MessageResponse */
        readonly MessageResponse: {
            /** Message */
            readonly message: string;
        };
        /** MitreContextItem */
        readonly MitreContextItem: {
            /** Name */
            readonly name: string;
            /** Relevance */
            readonly relevance: string;
            /** Tactics */
            readonly tactics: readonly string[];
            /** Technique Id */
            readonly technique_id: string;
        };
        /** MitreTechniqueListResponse */
        readonly MitreTechniqueListResponse: {
            /** Items */
            readonly items: readonly components["schemas"]["MitreTechniqueResponse"][];
            /** Limit */
            readonly limit: number;
            /** Offset */
            readonly offset: number;
            /** Total */
            readonly total: number;
        };
        /** MitreTechniqueResponse */
        readonly MitreTechniqueResponse: {
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
            /** Description */
            readonly description: string;
            /** External Id */
            readonly external_id: string;
            /** Is Subtechnique */
            readonly is_subtechnique: boolean;
            /** Name */
            readonly name: string;
            /** Parent External Id */
            readonly parent_external_id: string | null;
            /** Platforms */
            readonly platforms: readonly string[];
            /** Source Url */
            readonly source_url: string;
            /** Tactics */
            readonly tactics: readonly string[];
            /**
             * Updated At
             * Format: date-time
             */
            readonly updated_at: string;
            /** Version */
            readonly version: string;
        };
        /** Recommendation */
        readonly Recommendation: {
            /** Actions */
            readonly actions: readonly string[];
            /** Evidence Refs */
            readonly evidence_refs?: readonly string[];
            /**
             * Priority
             * @enum {string}
             */
            readonly priority: "low" | "medium" | "high" | "urgent";
            /** Rationale */
            readonly rationale: string;
            /** Title */
            readonly title: string;
        };
        /** RiskAnalysis */
        readonly RiskAnalysis: {
            /** Factors */
            readonly factors?: readonly string[];
            /** Rationale */
            readonly rationale: string;
            /** Score */
            readonly score: number;
            /**
             * Severity
             * @enum {string}
             */
            readonly severity: "low" | "medium" | "high" | "critical";
        };
        /** RuleTechniqueResponse */
        readonly RuleTechniqueResponse: {
            /** Rule Id */
            readonly rule_id: string;
            /** Techniques */
            readonly techniques: readonly components["schemas"]["MitreTechniqueResponse"][];
        };
        /** TimelineEntry */
        readonly TimelineEntry: {
            /** Alert Id */
            readonly alert_id?: string | null;
            /** Description */
            readonly description: string;
            /** Event Id */
            readonly event_id?: string | null;
            /** Metadata */
            readonly metadata?: {
                readonly [key: string]: unknown;
            };
            /** Rule Id */
            readonly rule_id?: string | null;
            /** Source Ip */
            readonly source_ip?: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            readonly timestamp: string;
            /** Title */
            readonly title: string;
            /** Type */
            readonly type: string;
            /** Username */
            readonly username?: string | null;
        };
        /** TokenResponse */
        readonly TokenResponse: {
            /** Access Token */
            readonly access_token: string;
            /** Expires In */
            readonly expires_in: number;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            readonly token_type: "bearer";
            readonly user: components["schemas"]["UserResponse"];
        };
        /** UserCreate */
        readonly UserCreate: {
            /**
             * Email
             * Format: email
             */
            readonly email: string;
            /** Full Name */
            readonly full_name: string;
            /** Password */
            readonly password: string;
            /**
             * Role Name
             * @enum {string}
             */
            readonly role_name: "admin" | "analyst" | "viewer";
        };
        /** UserListResponse */
        readonly UserListResponse: {
            /** Items */
            readonly items: readonly components["schemas"]["UserResponse"][];
            /** Limit */
            readonly limit: number;
            /** Offset */
            readonly offset: number;
            /** Total */
            readonly total: number;
        };
        /** UserResponse */
        readonly UserResponse: {
            /**
             * Created At
             * Format: date-time
             */
            readonly created_at: string;
            /**
             * Email
             * Format: email
             */
            readonly email: string;
            /** Full Name */
            readonly full_name: string;
            /**
             * Id
             * Format: uuid
             */
            readonly id: string;
            /** Is Active */
            readonly is_active: boolean;
            /** Last Login At */
            readonly last_login_at: string | null;
            /**
             * Role Name
             * @enum {string}
             */
            readonly role_name: "admin" | "analyst" | "viewer";
            /**
             * Updated At
             * Format: date-time
             */
            readonly updated_at: string;
        };
        /** UserUpdate */
        readonly UserUpdate: {
            /** Full Name */
            readonly full_name?: string | null;
            /** Is Active */
            readonly is_active?: boolean | null;
            /** Role Name */
            readonly role_name?: ("admin" | "analyst" | "viewer") | null;
        };
        /** ValidationError */
        readonly ValidationError: {
            /** Context */
            readonly ctx?: Record<string, never>;
            /** Input */
            readonly input?: unknown;
            /** Location */
            readonly loc: readonly (string | number)[];
            /** Message */
            readonly msg: string;
            /** Error Type */
            readonly type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly list_api_keys_api_v1_api_keys_get: {
        readonly parameters: {
            readonly query?: {
                readonly limit?: number;
                readonly offset?: number;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiKeyListResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly create_api_key_api_v1_api_keys_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["ApiKeyCreate"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiKeyCreatedResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly revoke_api_key_api_v1_api_keys__key_id__revoke_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly key_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ApiKeyResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly list_audit_logs_api_v1_audit_logs_get: {
        readonly parameters: {
            readonly query?: {
                readonly action?: string | null;
                readonly actor_id?: string | null;
                readonly actor_type?: string | null;
                readonly end_time?: string | null;
                readonly limit?: number;
                readonly offset?: number;
                readonly outcome?: string | null;
                readonly start_time?: string | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AuditLogListResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly change_password_api_v1_auth_change_password_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly login_api_v1_auth_login_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly logout_api_v1_auth_logout_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    readonly me_api_v1_auth_me_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    readonly refresh_api_v1_auth_refresh_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    readonly list_events_api_v1_events_get: {
        readonly parameters: {
            readonly query?: {
                readonly category?: ("authentication" | "network" | "cloud" | "application" | "file_access" | "privilege_change" | "process" | "api") | null;
                readonly end_time?: string | null;
                readonly event_type?: ("login_success" | "login_failure" | "logout" | "api_request" | "api_error" | "file_access" | "file_download" | "privilege_change" | "network_connection" | "network_scan" | "resource_access" | "account_created" | "account_deleted" | "password_changed") | null;
                readonly limit?: number;
                readonly offset?: number;
                readonly severity?: ("low" | "medium" | "high" | "critical") | null;
                readonly source_ip?: string | null;
                readonly start_time?: string | null;
                readonly username?: string | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["EventListResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly create_event_api_v1_events_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["EventCreate"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["EventIngestResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_event_api_v1_events__event_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly event_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["EventResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly create_events_bulk_api_v1_events_bulk_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["EventBulkCreate"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["EventBulkIngestResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly health_check_api_v1_health_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readonly list_incidents_api_v1_incidents_get: {
        readonly parameters: {
            readonly query?: {
                readonly limit?: number;
                readonly offset?: number;
                readonly severity?: ("low" | "medium" | "high" | "critical") | null;
                readonly source_ip?: string | null;
                readonly status?: ("open" | "investigating" | "contained" | "resolved") | null;
                readonly username?: string | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["IncidentListResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_incident_api_v1_incidents__incident_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly incident_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["IncidentDetail"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly list_incident_investigations_api_v1_incidents__incident_id__investigations_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly incident_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["InvestigationListResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly request_investigation_api_v1_incidents__incident_id__investigations_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly incident_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 202: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["InvestigationResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_investigation_api_v1_investigations__investigation_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly investigation_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["InvestigationResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_rule_techniques_api_v1_mitre_rules__rule_id__techniques_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly rule_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["RuleTechniqueResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly list_techniques_api_v1_mitre_techniques_get: {
        readonly parameters: {
            readonly query?: {
                readonly limit?: number;
                readonly offset?: number;
                readonly search?: string | null;
                readonly tactic?: string | null;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["MitreTechniqueListResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_technique_api_v1_mitre_techniques__external_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly external_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["MitreTechniqueResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly list_users_api_v1_users_get: {
        readonly parameters: {
            readonly query?: {
                readonly limit?: number;
                readonly offset?: number;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["UserListResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly create_user_api_v1_users_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["UserCreate"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly get_user_api_v1_users__user_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly user_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readonly update_user_api_v1_users__user_id__patch: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly user_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["UserUpdate"];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
